site_name: 'Awesome Python'
site_url: 'https://awesome-python.com'
site_description: 'A curated list of awesome Python frameworks, libraries and software'
site_author: 'Vinta Chen'
repo_name: 'vinta/awesome-python'
repo_url: 'https://github.com/vinta/awesome-python'
theme: 'material'
extra:
  feature:
    tabs: false
  palette:
    primary: 'red'
    accent: 'pink'
  social:
    - type: 'github'
      link: 'https://github.com/vinta'
    - type: 'twitter'
      link: 'https://twitter.com/vinta'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/vinta'
google_analytics:
  - 'UA-510626-7'
  - 'auto'
extra_css:
    - css/extra.css
pages:
  - "Life is short, you need Python.": "index.md"
